export const publicExpoEnvNames = [
  'EXPO_PUBLIC_APP_ENV',
  'EXPO_PUBLIC_APP_SCHEME',
  'EXPO_PUBLIC_DEFAULT_INSTANCE_ID',
  'EXPO_PUBLIC_DEFAULT_INSTANCE_NAME',
  'EXPO_PUBLIC_DEFAULT_INSTANCE_URL',
  'EXPO_PUBLIC_DEFAULT_CONVEX_URL',
  'EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY',
  'EXPO_PUBLIC_REVENUECAT_IOS_API_KEY',
  'EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY',
] as const;

export const serverSecretEnvNames = [
  'INSTANCE_BASE_URL',
  'CLERK_JWT_ISSUER_DOMAIN',
  'REVENUECAT_WEBHOOK_AUTH',
  'S3_BUCKET',
  'S3_REGION',
  'S3_ENDPOINT',
  'S3_BASE_PATH',
  'S3_ACCESS_KEY_ID',
  'S3_SECRET_ACCESS_KEY',
  'EXPO_TOKEN',
] as const;

export function isPublicExpoVariable(name: string): boolean {
  return name.startsWith('EXPO_PUBLIC_');
}
