export const publicExpoEnvNames = [
  'EXPO_PUBLIC_APP_ENV',
  'EXPO_PUBLIC_APP_SCHEME',
  'EXPO_PUBLIC_DEFAULT_INSTANCE_ID',
  'EXPO_PUBLIC_DEFAULT_INSTANCE_NAME',
  'EXPO_PUBLIC_DEFAULT_INSTANCE_URL',
  'EXPO_PUBLIC_DEFAULT_CONVEX_URL',
  'EXPO_PUBLIC_DEFAULT_AUTH_MODE',
  'EXPO_PUBLIC_DEFAULT_AUTH_CLIENT_ID',
  'EXPO_PUBLIC_DEFAULT_AUTH_SIGN_IN_URL',
] as const;

export const serverSecretEnvNames = [
  'INSTANCE_BASE_URL',
  'WORKOS_API_KEY',
  'WORKOS_CLIENT_ID',
  'WORKOS_COOKIE_PASSWORD',
  'S3_BUCKET',
  'S3_REGION',
  'S3_ENDPOINT',
  'S3_BASE_PATH',
  'S3_ACCESS_KEY_ID',
  'S3_SECRET_ACCESS_KEY',
  'EXPO_TOKEN',
] as const;

export function isPublicExpoVariable(name: string): boolean {
  return name.startsWith('EXPO_PUBLIC_');
}
